// Verifica si la colección 'compras' existe y la elimina si es así
if (db.getCollectionNames().indexOf('compras') !== -1) {
    db.compras.drop(); // Elimina la colección si existe
}

// Crea la colección 'compras' y agrega documentos de ejemplo
db.createCollection('compras');

// Inserta varios documentos con información sobre compras de productos de tecnología
db.compras.insertMany([
    {
        fecha_compra: new Date('2024-11-15'),
        nombre_cliente: 'Juan Pérez',
        edad_cliente: 30,
        producto: 'Laptop',
        categoria: 'Tecnología',
        marca: 'Dell',
        modelo: 'Inspiron 15',
        precio: 750.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 100 # 7-80, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-17'),
        nombre_cliente: 'María Gómez',
        edad_cliente: 25,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Apple',
        modelo: 'iPhone 15',
        precio: 999.00,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Carrera 15 # 93-10, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-18'),
        nombre_cliente: 'Carlos Martínez',
        edad_cliente: 35,
        producto: 'Smartwatch',
        categoria: 'Tecnología',
        marca: 'Samsung',
        modelo: 'Galaxy Watch 6',
        precio: 299.99,
        cantidad: 2,
        metodo_pago: 'Tarjeta de débito',
        direccion_envio: 'Avenida NQS # 45-78, Bogotá, Colombia',
        estado_envio: 'En tránsito'
    },
    {
        fecha_compra: new Date('2024-11-19'),
        nombre_cliente: 'Laura Fernández',
        edad_cliente: 28,
        producto: 'Auriculares',
        categoria: 'Tecnología',
        marca: 'Sony',
        modelo: 'WH-1000XM5',
        precio: 349.99,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 26 # 69-10, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'José Martínez',
        edad_cliente: 32,
        producto: 'Laptop',
        categoria: 'Tecnología',
        marca: 'Acer',
        modelo: 'Aspire 5',
        precio: 699.99,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 34 # 15-10, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Lucía González',
        edad_cliente: 27,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Xiaomi',
        modelo: 'Redmi Note 13',
        precio: 299.99,
        cantidad: 1,
        metodo_pago: 'Tarjeta de débito',
        direccion_envio: 'Carrera 45 # 22-10, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Antonio Fernández',
        edad_cliente: 40,
        producto: 'Smartwatch',
        categoria: 'Tecnología',
        marca: 'Garmin',
        modelo: 'Forerunner 945',
        precio: 549.99,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Avenida 60 # 45-12, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Isabel Romero',
        edad_cliente: 35,
        producto: 'Auriculares',
        categoria: 'Tecnología',
        marca: 'Sennheiser',
        modelo: 'Momentum 3',
        precio: 399.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 18 # 20-50, Bogotá, Colombia',
        estado_envio: 'En tránsito'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'David Ruiz',
        edad_cliente: 29,
        producto: 'Tablet',
        categoria: 'Tecnología',
        marca: 'Microsoft',
        modelo: 'Surface Pro 8',
        precio: 899.99,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 50 # 31-15, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Carlos Herrera',
        edad_cliente: 33,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Motorola',
        modelo: 'Edge 40',
        precio: 499.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de débito',
        direccion_envio: 'Calle 80 # 11-20, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Paula Pérez',
        edad_cliente: 26,
        producto: 'Auriculares',
        categoria: 'Tecnología',
        marca: 'Bose',
        modelo: 'QuietComfort 35 II',
        precio: 299.00,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Carrera 10 # 30-15, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Felipe Jiménez',
        edad_cliente: 41,
        producto: 'Laptop',
        categoria: 'Tecnología',
        marca: 'Asus',
        modelo: 'ZenBook 14',
        precio: 799.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 30 # 27-13, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'María Sánchez',
        edad_cliente: 34,
        producto: 'Smartwatch',
        categoria: 'Tecnología',
        marca: 'Apple',
        modelo: 'Watch Ultra',
        precio: 799.00,
        cantidad: 1,
        metodo_pago: 'Transferencia bancaria',
        direccion_envio: 'Carrera 65 # 20-10, Bogotá, Colombia',
        estado_envio: 'En tránsito'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Javier Castro',
        edad_cliente: 30,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'OnePlus',
        modelo: 'OnePlus 11',
        precio: 749.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Avenida 23 # 18-50, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Lina Martínez',
        edad_cliente: 26,
        producto: 'Laptop',
        categoria: 'Tecnología',
        marca: 'Lenovo',
        modelo: 'IdeaPad 3',
        precio: 599.99,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 44 # 15-10, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Carlos Medina',
        edad_cliente: 45,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Huawei',
        modelo: 'P60 Pro',
        precio: 999.00,
        cantidad: 1,
        metodo_pago: 'Transferencia bancaria',
        direccion_envio: 'Carrera 50 # 22-30, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Marta López',
        edad_cliente: 38,
        producto: 'Smartwatch',
        categoria: 'Tecnología',
        marca: 'Fossil',
        modelo: 'Hybrid HR',
        precio: 199.99,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Calle 35 # 12-45, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Andrés Ríos',
        edad_cliente: 29,
        producto: 'Auriculares',
        categoria: 'Tecnología',
        marca: 'Sony',
        modelo: 'WH-CH710N',
        precio: 129.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 21 # 8-60, Bogotá, Colombia',
        estado_envio: 'En tránsito'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Patricia Fernández',
        edad_cliente: 41,
        producto: 'Tablet',
        categoria: 'Tecnología',
        marca: 'Apple',
        modelo: 'iPad Pro 11',
        precio: 799.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Carrera 80 # 25-40, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Víctor Gutiérrez',
        edad_cliente: 33,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Google',
        modelo: 'Pixel 8 Pro',
        precio: 899.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de débito',
        direccion_envio: 'Avenida 75 # 18-60, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Jorge García',
        edad_cliente: 30,
        producto: 'Auriculares',
        categoria: 'Tecnología',
        marca: 'Bose',
        modelo: 'Noise Cancelling Headphones 700',
        precio: 379.00,
        cantidad: 1,
        metodo_pago: 'Transferencia bancaria',
        direccion_envio: 'Calle 90 # 5-30, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Alejandra Díaz',
        edad_cliente: 27,
        producto: 'Laptop',
        categoria: 'Tecnología',
        marca: 'HP',
        modelo: 'Envy 13',
        precio: 849.00,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Calle 60 # 10-20, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Ricardo Pérez',
        edad_cliente: 36,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Samsung',
        modelo: 'Galaxy Z Fold 5',
        precio: 1799.99,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Carrera 24 # 50-25, Bogotá, Colombia',
        estado_envio: 'En tránsito'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Sofía Romero',
        edad_cliente: 29,
        producto: 'Smartwatch',
        categoria: 'Tecnología',
        marca: 'Apple',
        modelo: 'Watch Series 8',
        precio: 399.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de débito',
        direccion_envio: 'Avenida 30 # 10-15, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Martín Álvarez',
        edad_cliente: 34,
        producto: 'Laptop',
        categoria: 'Tecnología',
        marca: 'Apple',
        modelo: 'MacBook Air M2',
        precio: 1199.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 21 # 19-80, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Beatriz González',
        edad_cliente: 32,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Xiaomi',
        modelo: 'Mi 13',
        precio: 649.99,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Avenida 45 # 12-40, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Miguel Torres',
        edad_cliente: 29,
        producto: 'Smartwatch',
        categoria: 'Tecnología',
        marca: 'Fitbit',
        modelo: 'Sense 2',
        precio: 299.99,
        cantidad: 1,
        metodo_pago: 'Tarjeta de débito',
        direccion_envio: 'Calle 15 # 23-10, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Carolina Silva',
        edad_cliente: 39,
        producto: 'Auriculares',
        categoria: 'Tecnología',
        marca: 'JBL',
        modelo: 'Club 950NC',
        precio: 249.00,
        cantidad: 1,
        metodo_pago: 'Transferencia bancaria',
        direccion_envio: 'Carrera 80 # 7-90, Bogotá, Colombia',
        estado_envio: 'En tránsito'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Eduardo Pérez',
        edad_cliente: 27,
        producto: 'Tablet',
        categoria: 'Tecnología',
        marca: 'Samsung',
        modelo: 'Galaxy Tab S7',
        precio: 699.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 28 # 16-50, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Ángel García',
        edad_cliente: 33,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'OnePlus',
        modelo: 'OnePlus 10T',
        precio: 649.99,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Avenida 25 # 30-25, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Isabel Martínez',
        edad_cliente: 42,
        producto: 'Auriculares',
        categoria: 'Tecnología',
        marca: 'Bang & Olufsen',
        modelo: 'Beoplay HX',
        precio: 499.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de débito',
        direccion_envio: 'Calle 17 # 22-60, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'José Luis Romero',
        edad_cliente: 35,
        producto: 'Laptop',
        categoria: 'Tecnología',
        marca: 'Dell',
        modelo: 'XPS 13',
        precio: 1299.00,
        cantidad: 1,
        metodo_pago: 'Transferencia bancaria',
        direccion_envio: 'Calle 40 # 15-25, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Patricia González',
        edad_cliente: 31,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Google',
        modelo: 'Pixel 8',
        precio: 799.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 12 # 10-30, Bogotá, Colombia',
        estado_envio: 'En tránsito'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Víctor Hernández',
        edad_cliente: 37,
        producto: 'Smartwatch',
        categoria: 'Tecnología',
        marca: 'Suunto',
        modelo: 'Suunto 9 Peak',
        precio: 549.00,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Carrera 18 # 25-50, Bogotá, Colombia',
        estado_envio: 'Entregado'
    }, 
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Luis Morales',
        edad_cliente: 28,
        producto: 'Laptop',
        categoria: 'Tecnología',
        marca: 'MSI',
        modelo: 'GF63 Thin',
        precio: 899.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 15 # 8-25, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Verónica Herrera',
        edad_cliente: 31,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Samsung',
        modelo: 'Galaxy S24',
        precio: 1099.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de débito',
        direccion_envio: 'Calle 60 # 34-50, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Fernando González',
        edad_cliente: 34,
        producto: 'Smartwatch',
        categoria: 'Tecnología',
        marca: 'Garmin',
        modelo: 'Venu 2',
        precio: 399.99,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Carrera 40 # 28-10, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Claudia López',
        edad_cliente: 29,
        producto: 'Auriculares',
        categoria: 'Tecnología',
        marca: 'Sony',
        modelo: 'WF-1000XM4',
        precio: 249.99,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Avenida 55 # 20-30, Bogotá, Colombia',
        estado_envio: 'En tránsito'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Diego Pérez',
        edad_cliente: 38,
        producto: 'Tablet',
        categoria: 'Tecnología',
        marca: 'Huawei',
        modelo: 'MatePad Pro',
        precio: 649.00,
        cantidad: 1,
        metodo_pago: 'Transferencia bancaria',
        direccion_envio: 'Calle 75 # 10-35, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Raquel Fernández',
        edad_cliente: 33,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Oppo',
        modelo: 'Find X5 Pro',
        precio: 999.00,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Calle 40 # 12-55, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Patricia Ruiz',
        edad_cliente: 30,
        producto: 'Auriculares',
        categoria: 'Tecnología',
        marca: 'JBL',
        modelo: 'Quantum One',
        precio: 349.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 62 # 5-70, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Carlos López',
        edad_cliente: 36,
        producto: 'Laptop',
        categoria: 'Tecnología',
        marca: 'HP',
        modelo: 'Pavilion 15',
        precio: 799.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de débito',
        direccion_envio: 'Avenida 100 # 12-80, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'José Martínez',
        edad_cliente: 42,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Apple',
        modelo: 'iPhone 14 Pro',
        precio: 1099.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 100 # 30-10, Bogotá, Colombia',
        estado_envio: 'En tránsito'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Margarita Díaz',
        edad_cliente: 26,
        producto: 'Smartwatch',
        categoria: 'Tecnología',
        marca: 'Fossil',
        modelo: 'Hybrid HR',
        precio: 249.99,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Calle 38 # 14-25, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Marco Torres',
        edad_cliente: 27,
        producto: 'Laptop',
        categoria: 'Tecnología',
        marca: 'Acer',
        modelo: 'Aspire 5',
        precio: 599.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 56 # 21-45, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Gabriela Castro',
        edad_cliente: 30,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Realme',
        modelo: 'GT 2 Pro',
        precio: 749.99,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Calle 22 # 3-25, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Luis González',
        edad_cliente: 32,
        producto: 'Smartwatch',
        categoria: 'Tecnología',
        marca: 'Suunto',
        modelo: 'Suunto 7',
        precio: 399.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de débito',
        direccion_envio: 'Avenida 50 # 16-30, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Ana Rivera',
        edad_cliente: 35,
        producto: 'Auriculares',
        categoria: 'Tecnología',
        marca: 'Bose',
        modelo: 'QuietComfort 45',
        precio: 329.99,
        cantidad: 1,
        metodo_pago: 'Transferencia bancaria',
        direccion_envio: 'Calle 9 # 7-60, Bogotá, Colombia',
        estado_envio: 'En tránsito'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Santiago García',
        edad_cliente: 40,
        producto: 'Tablet',
        categoria: 'Tecnología',
        marca: 'Lenovo',
        modelo: 'Tab P11',
        precio: 349.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 30 # 15-10, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Juliana López',
        edad_cliente: 29,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Sony',
        modelo: 'Xperia 1 IV',
        precio: 1199.00,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Avenida 22 # 10-60, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Felipe Márquez',
        edad_cliente: 31,
        producto: 'Auriculares',
        categoria: 'Tecnología',
        marca: 'JBL',
        modelo: 'Live Pro+',
        precio: 249.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 48 # 8-75, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Verónica Ríos',
        edad_cliente: 34,
        producto: 'Laptop',
        categoria: 'Tecnología',
        marca: 'Asus',
        modelo: 'ZenBook 14',
        precio: 899.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de débito',
        direccion_envio: 'Calle 12 # 3-15, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Mario Fernández',
        edad_cliente: 37,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Motorola',
        modelo: 'Edge 40',
        precio: 649.00,
        cantidad: 1,
        metodo_pago: 'Transferencia bancaria',
        direccion_envio: 'Calle 70 # 18-40, Bogotá, Colombia',
        estado_envio: 'En tránsito'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Sandra Sánchez',
        edad_cliente: 30,
        producto: 'Smartwatch',
        categoria: 'Tecnología',
        marca: 'Garmin',
        modelo: 'Venu 2 Plus',
        precio: 399.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 19 # 22-15, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Pedro Martínez',
        edad_cliente: 26,
        producto: 'Laptop',
        categoria: 'Tecnología',
        marca: 'Lenovo',
        modelo: 'Legion 5',
        precio: 1099.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Avenida 100 # 5-20, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Isabel Ríos',
        edad_cliente: 31,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Huawei',
        modelo: 'P50 Pro',
        precio: 999.00,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Calle 14 # 17-50, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Cristian Gómez',
        edad_cliente: 35,
        producto: 'Smartwatch',
        categoria: 'Tecnología',
        marca: 'Amazfit',
        modelo: 'GTR 4',
        precio: 229.99,
        cantidad: 1,
        metodo_pago: 'Tarjeta de débito',
        direccion_envio: 'Carrera 35 # 10-60, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Patricia Martínez',
        edad_cliente: 40,
        producto: 'Auriculares',
        categoria: 'Tecnología',
        marca: 'Sennheiser',
        modelo: 'Momentum 3',
        precio: 399.00,
        cantidad: 1,
        metodo_pago: 'Transferencia bancaria',
        direccion_envio: 'Calle 38 # 25-70, Bogotá, Colombia',
        estado_envio: 'En tránsito'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Andrés Álvarez',
        edad_cliente: 33,
        producto: 'Tablet',
        categoria: 'Tecnología',
        marca: 'Apple',
        modelo: 'iPad Air',
        precio: 699.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 55 # 16-10, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Carmen Gómez',
        edad_cliente: 38,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Nokia',
        modelo: 'X30',
        precio: 499.00,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Carrera 18 # 5-35, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Eduardo Pérez',
        edad_cliente: 30,
        producto: 'Auriculares',
        categoria: 'Tecnología',
        marca: 'Bose',
        modelo: 'SoundSport Free',
        precio: 199.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de débito',
        direccion_envio: 'Calle 22 # 30-60, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Verónica López',
        edad_cliente: 29,
        producto: 'Smartwatch',
        categoria: 'Tecnología',
        marca: 'Polar',
        modelo: 'Vantage M2',
        precio: 249.00,
        cantidad: 1,
        metodo_pago: 'Transferencia bancaria',
        direccion_envio: 'Avenida 55 # 17-80, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Ricardo Sánchez',
        edad_cliente: 42,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Samsung',
        modelo: 'Galaxy Z Flip 5',
        precio: 1799.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 70 # 30-90, Bogotá, Colombia',
        estado_envio: 'En tránsito'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Sofía Díaz',
        edad_cliente: 34,
        producto: 'Laptop',
        categoria: 'Tecnología',
        marca: 'Apple',
        modelo: 'MacBook Pro 16"',
        precio: 2399.00,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Calle 33 # 22-10, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Álvaro Torres',
        edad_cliente: 27,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Xiaomi',
        modelo: '12T Pro',
        precio: 899.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 50 # 15-40, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Lucía Rodríguez',
        edad_cliente: 29,
        producto: 'Smartwatch',
        categoria: 'Tecnología',
        marca: 'Fitbit',
        modelo: 'Sense 2',
        precio: 299.00,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Avenida 44 # 18-15, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Carlos Herrera',
        edad_cliente: 31,
        producto: 'Auriculares',
        categoria: 'Tecnología',
        marca: 'Apple',
        modelo: 'AirPods Pro 2',
        precio: 249.00,
        cantidad: 1,
        metodo_pago: 'Transferencia bancaria',
        direccion_envio: 'Calle 12 # 8-50, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'María Pérez',
        edad_cliente: 32,
        producto: 'Laptop',
        categoria: 'Tecnología',
        marca: 'HP',
        modelo: 'Envy x360',
        precio: 1199.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 18 # 11-70, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Ricardo Pérez',
        edad_cliente: 40,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Google',
        modelo: 'Pixel 8',
        precio: 799.00,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Carrera 45 # 22-25, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Patricia Martínez',
        edad_cliente: 36,
        producto: 'Tablet',
        categoria: 'Tecnología',
        marca: 'Samsung',
        modelo: 'Galaxy Tab S8',
        precio: 649.00,
        cantidad: 1,
        metodo_pago: 'Transferencia bancaria',
        direccion_envio: 'Avenida 10 # 13-40, Bogotá, Colombia',
        estado_envio: 'En tránsito'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Jorge Gómez',
        edad_cliente: 33,
        producto: 'Smartwatch',
        categoria: 'Tecnología',
        marca: 'Samsung',
        modelo: 'Galaxy Watch 6 Classic',
        precio: 349.99,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 70 # 14-10, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Daniela López',
        edad_cliente: 30,
        producto: 'Auriculares',
        categoria: 'Tecnología',
        marca: 'Sony',
        modelo: 'WH-XB910N',
        precio: 199.99,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Calle 32 # 17-60, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Juan Carlos Rodríguez',
        edad_cliente: 28,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'OnePlus',
        modelo: '11 5G',
        precio: 749.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 45 # 8-90, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Esteban Sánchez',
        edad_cliente: 34,
        producto: 'Laptop',
        categoria: 'Tecnología',
        marca: 'Apple',
        modelo: 'MacBook Air M2',
        precio: 1499.00,
        cantidad: 1,
        metodo_pago: 'Transferencia bancaria',
        direccion_envio: 'Calle 25 # 22-15, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Natalia Vásquez',
        edad_cliente: 27,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Realme',
        modelo: 'Narzo 60',
        precio: 499.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de débito',
        direccion_envio: 'Calle 16 # 8-90, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Carlos Soto',
        edad_cliente: 34,
        producto: 'Tablet',
        categoria: 'Tecnología',
        marca: 'Huawei',
        modelo: 'MatePad 11',
        precio: 499.00,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Carrera 70 # 4-35, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'María Jiménez',
        edad_cliente: 40,
        producto: 'Auriculares',
        categoria: 'Tecnología',
        marca: 'JBL',
        modelo: 'Tune 760NC',
        precio: 129.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 20 # 12-60, Bogotá, Colombia',
        estado_envio: 'En tránsito'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Felipe Gómez',
        edad_cliente: 29,
        producto: 'Laptop',
        categoria: 'Tecnología',
        marca: 'Dell',
        modelo: 'XPS 13',
        precio: 1299.00,
        cantidad: 1,
        metodo_pago: 'Transferencia bancaria',
        direccion_envio: 'Avenida 35 # 7-50, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Sandra González',
        edad_cliente: 30,
        producto: 'Smartwatch',
        categoria: 'Tecnología',
        marca: 'Garmin',
        modelo: 'Forerunner 955',
        precio: 499.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 44 # 8-15, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Juan Sánchez',
        edad_cliente: 33,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Oppo',
        modelo: 'Find X5 Pro',
        precio: 1099.00,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Calle 58 # 11-50, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Esteban Fernández',
        edad_cliente: 28,
        producto: 'Auriculares',
        categoria: 'Tecnología',
        marca: 'Sony',
        modelo: 'WF-1000XM5',
        precio: 279.99,
        cantidad: 1,
        metodo_pago: 'Transferencia bancaria',
        direccion_envio: 'Calle 30 # 17-90, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Andrea López',
        edad_cliente: 35,
        producto: 'Tablet',
        categoria: 'Tecnología',
        marca: 'Apple',
        modelo: 'iPad Pro 12.9"',
        precio: 1299.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 12 # 10-40, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Juan Carlos López',
        edad_cliente: 37,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Samsung',
        modelo: 'Galaxy S24',
        precio: 999.00,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Avenida 33 # 18-30, Bogotá, Colombia',
        estado_envio: 'En tránsito'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Laura Martínez',
        edad_cliente: 31,
        producto: 'Smartwatch',
        categoria: 'Tecnología',
        marca: 'Apple',
        modelo: 'Apple Watch Series 8',
        precio: 399.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 50 # 3-60, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Esteban Fernández',
        edad_cliente: 28,
        producto: 'Auriculares',
        categoria: 'Tecnología',
        marca: 'Sony',
        modelo: 'WF-1000XM5',
        precio: 279.99,
        cantidad: 1,
        metodo_pago: 'Transferencia bancaria',
        direccion_envio: 'Calle 30 # 17-90, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Andrea López',
        edad_cliente: 35,
        producto: 'Tablet',
        categoria: 'Tecnología',
        marca: 'Apple',
        modelo: 'iPad Pro 12.9"',
        precio: 1299.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 12 # 10-40, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Juan Carlos López',
        edad_cliente: 37,
        producto: 'Smartphone',
        categoria: 'Tecnología',
        marca: 'Samsung',
        modelo: 'Galaxy S24',
        precio: 999.00,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Avenida 33 # 18-30, Bogotá, Colombia',
        estado_envio: 'En tránsito'
    },
    {
        fecha_compra: new Date('2024-11-20'),
        nombre_cliente: 'Laura Martínez',
        edad_cliente: 31,
        producto: 'Smartwatch',
        categoria: 'Tecnología',
        marca: 'Apple',
        modelo: 'Apple Watch Series 8',
        precio: 399.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 50 # 3-60, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-21'),
        nombre_cliente: 'Fernando Salazar',
        edad_cliente: 39,
        producto: 'Consola de videojuegos',
        categoria: 'Entretenimiento',
        marca: 'Sony',
        modelo: 'PlayStation 5',
        precio: 499.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 100 # 15-30, Bogotá, Colombia',
        estado_envio: 'En tránsito'
    },
    {
        fecha_compra: new Date('2024-11-21'),
        nombre_cliente: 'Natalia Pérez',
        edad_cliente: 33,
        producto: 'Teclado mecánico',
        categoria: 'Tecnología',
        marca: 'Razer',
        modelo: 'BlackWidow V4',
        precio: 199.99,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Carrera 11 # 98-15, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-21'),
        nombre_cliente: 'Mauricio López',
        edad_cliente: 28,
        producto: 'Router Wi-Fi',
        categoria: 'Tecnología',
        marca: 'TP-Link',
        modelo: 'Archer AX73',
        precio: 179.99,
        cantidad: 1,
        metodo_pago: 'Transferencia bancaria',
        direccion_envio: 'Carrera 50 # 40-10, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-21'),
        nombre_cliente: 'Andrea Castro',
        edad_cliente: 35,
        producto: 'Smart TV',
        categoria: 'Electrodomésticos',
        marca: 'LG',
        modelo: 'OLED 65"',
        precio: 1999.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de débito',
        direccion_envio: 'Calle 7 # 20-45, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-21'),
        nombre_cliente: 'Valentina Rojas',
        edad_cliente: 26,
        producto: 'Cámara de acción',
        categoria: 'Fotografía',
        marca: 'GoPro',
        modelo: 'Hero 12 Black',
        precio: 399.99,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 19 # 34-70, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-21'),
        nombre_cliente: 'Julio Morales',
        edad_cliente: 38,
        producto: 'Barra de sonido',
        categoria: 'Audio',
        marca: 'Sonos',
        modelo: 'Arc',
        precio: 899.99,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Carrera 28 # 16-30, Bogotá, Colombia',
        estado_envio: 'En tránsito'
    },
    {
        fecha_compra: new Date('2024-11-21'),
        nombre_cliente: 'Claudia Restrepo',
        edad_cliente: 41,
        producto: 'Tablet',
        categoria: 'Tecnología',
        marca: 'Samsung',
        modelo: 'Galaxy Tab S9',
        precio: 1099.00,
        cantidad: 1,
        metodo_pago: 'Transferencia bancaria',
        direccion_envio: 'Carrera 60 # 22-90, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-21'),
        nombre_cliente: 'Roberto Acosta',
        edad_cliente: 45,
        producto: 'Refrigerador',
        categoria: 'Electrodomésticos',
        marca: 'LG',
        modelo: 'InstaView Door-in-Door',
        precio: 2499.00,
        cantidad: 1,
        metodo_pago: 'Tarjeta de crédito',
        direccion_envio: 'Calle 55 # 17-80, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-21'),
        nombre_cliente: 'Liliana Vargas',
        edad_cliente: 29,
        producto: 'Parlante portátil',
        categoria: 'Tecnología',
        marca: 'Sony',
        modelo: 'SRS-XG300',
        precio: 349.99,
        cantidad: 1,
        metodo_pago: 'Tarjeta de débito',
        direccion_envio: 'Carrera 18 # 8-25, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-21'),
        nombre_cliente: 'Pablo Silva',
        edad_cliente: 32,
        producto: 'Cargador inalámbrico',
        categoria: 'Accesorios',
        marca: 'Belkin',
        modelo: 'Boost Charge Pro',
        precio: 79.99,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Calle 80 # 20-60, Bogotá, Colombia',
        estado_envio: 'En tránsito'
    },
    {
        fecha_compra: new Date('2024-11-21'),
        nombre_cliente: 'Carolina Espinosa',
        edad_cliente: 36,
        producto: 'Aspiradora robot',
        categoria: 'Electrodomésticos',
        marca: 'iRobot',
        modelo: 'Roomba i7+',
        precio: 799.00,
        cantidad: 1,
        metodo_pago: 'Transferencia bancaria',
        direccion_envio: 'Carrera 12 # 50-75, Bogotá, Colombia',
        estado_envio: 'Entregado'
    },
    {
        fecha_compra: new Date('2024-11-21'),
        nombre_cliente: 'Daniel Torres',
        edad_cliente: 33,
        producto: 'Auriculares gaming',
        categoria: 'Tecnología',
        marca: 'HyperX',
        modelo: 'Cloud Alpha Wireless',
        precio: 199.99,
        cantidad: 1,
        metodo_pago: 'Tarjeta de débito',
        direccion_envio: 'Calle 10 # 30-40, Bogotá, Colombia',
        estado_envio: 'Enviado'
    },
    {
        fecha_compra: new Date('2024-11-21'),
        nombre_cliente: 'Margarita Ortiz',
        edad_cliente: 40,
        producto: 'Smartwatch',
        categoria: 'Tecnología',
        marca: 'Garmin',
        modelo: 'Forerunner 965',
        precio: 499.99,
        cantidad: 1,
        metodo_pago: 'PayPal',
        direccion_envio: 'Carrera 7 # 45-50, Bogotá, Colombia',
        estado_envio: 'En tránsito'
    },
    {
        fecha_compra: new Date('2024-11-21'),
        nombre_cliente: 'Luis Cárdenas',
        edad_cliente: 28,
        producto: 'Disco duro externo',
        categoria: 'Almacenamiento',
        marca: 'Seagate',
        modelo: 'Backup Plus 5TB',
        precio: 129.99,
        cantidad: 1,
        metodo_pago: 'Transferencia bancaria',
        direccion_envio: 'Calle 90 # 18-40, Bogotá, Colombia',
        estado_envio: 'Entregado'
    }
]);

// Verifica que los documentos han sido insertados correctamente
print('Compras insertadas:');
db.compras.find().pretty();
